import { ROLE, n } from './format'

export const MESSAGES = {
  name_required: '名稱不能空白',
  not_a_directory: '不是資料夾',
  unreadable_directory: '無法讀取資料夾',
  collection_not_found: '找不到收藏庫',
  collection_exists: d => `已有名為「${d.name}」的收藏庫`,
  collection_root_change: '位置請用「變更位置」修改',
  collection_holds_works: d => `收藏庫還有 ${n(d.works)} 部作品，無法移除`,
  relocate_conflict: '新位置有路徑已登記，未變更',
  outside_collections: '路徑不在任何收藏庫內',
  inside_collections: '路徑在收藏庫內，請改用掃描',
  path_missing: '路徑不存在',
  place_unknown: '路徑沒有登記作品',
  last_copy: '僅剩一份，無法丟棄',
  recycle_refused: '無法移到資源回收筒，未刪除任何檔案',
  no_frame: '影片沒有可讀取的畫面',
  no_images: '作品沒有圖片',
  page_out_of_range: '頁碼超出範圍',
  paths_required: '未選取路徑',
  not_registrable: '不是資料夾或影片檔',
  profile_has_no_members: '模型設定檔沒有模型',
  no_embedding_model: '使用中的設定檔沒有向量模型',
  job_not_found: '找不到工作',
  check_not_found: '找不到檢查重複的工作',
  job_not_running: '工作已結束，無法取消',
  job_not_retryable: '只有失敗或已取消的工作能重試',
  job_not_finished: '工作尚未結束，無法刪除',
  job_profile_deleted: '工作的設定檔已刪除，無法重試',
  no_match: '沒有對應的作品',
  already_discarded: '已丟棄',
  library_copy_missing: '收藏庫內的副本不在磁碟上，無法丟棄',
  worker_running: '掃描程序已在執行',
  worker_start_timeout: '掃描程序啟動逾時，請查看記錄',
  profile_not_found: '找不到模型設定檔',
  profile_exists: d => `已有名為「${d.name}」的設定檔`,
  profile_is_active: '無法刪除使用中的設定檔',
  profile_has_jobs: d => `設定檔還有 ${n(d.jobs)} 個未結束的工作`,
  profile_active_required: '請將另一個設定檔設為使用中',
  profile_active_maintained: '使用中的設定檔必須保持更新',
  profile_needs_embedding: '設定檔必須剛好有一個向量模型',
  profile_not_derived: d => `設定檔尚未計算完成（${n(d.derived)} / ${n(d.works)}）`,
  model_not_found: '找不到模型',
  member_not_found: '設定檔中沒有這個模型',
  role_unknown: '不明的類別',
  role_taken: d => `${ROLE[d.role] || d.role}已由 ${d.backend} 負責`,
  param_not_found: '找不到參數',
  no_ready_version: '模型沒有建置完成的版本',
  definition_invalid: d => `定義有誤：${d.message}`,
  definition_not_found: '找不到模型定義',
  definition_retracted: '定義已撤回，無法建置',
  definition_unpinned: '定義沒有指定修訂版，無法建置',
  version_exists: d => (d.state === 'ready' ? '這個精度的版本已建置' : '這個精度的版本正在建置'),
  version_not_found: '找不到版本',
  version_not_ready: '版本尚未建置完成',
  version_in_use: d => `設定檔「${(d.profiles || []).join('」、「')}」使用中，無法刪除`,
  version_building: '版本建置中，無法刪除',
  concept_not_found: '找不到詞彙',
  term_not_found: '找不到別名',
  slug_required: '名稱不能空白',
  concept_exists: d => `已有「${d.slug}」，可改用合併`,
  concept_enum: '分級、色彩、類型無法修改',
  parent_not_series: '所屬系列必須是系列',
  parent_cycle: '所屬系列形成循環',
  merge_into_self: '無法合併到自己',
  concept_kind_mismatch: '種類不符',
  concept_in_use: d => `仍有 ${n(d.claims)} 筆宣告、${n(d.children)} 個下層項目，無法刪除；可改用合併`,
  invalid_override: '修改內容不正確',
  work_not_found: '找不到作品',
  claim_not_found: '找不到這筆宣告',
  field_unknown: '不明的欄位',
  value_required: '未填值',
  concept_unknown: d => `詞彙中沒有「${d.value}」`,
}

export function explain(e) {
  const m = MESSAGES[e?.code]
  if (typeof m === 'function') return m(e.detail || {})
  return m || e?.message || String(e)
}
