export const GROUPS = {
  score: '標籤分數門檻', freq: '出現頻率', freqz: '頻率信心',
  rating: '分級', type: '作品類型', cg: 'CG 集判定',
  check: '檢查重複', worker: '掃描程序',
  sample: '抽樣', video: '影片抽格', color: '色彩',
}

export const LABELS = {
  'check:near': '近似作品的相似度下限',
  'cg:aspect_std': 'CG 集的長寬比標準差上限',
  'cg:max_images': 'CG 集的圖片數上限',
  'cg:min_avg_size': 'CG 集的平均像素數下限',
  'cg:min_images': 'CG 集的圖片數下限',
  'cg:seq_ratio': 'CG 集的連號檔名比例下限',
  'color:full': '全彩的彩頁比例下限',
  'color:gray': '黑白的彩頁比例上限',
  'color:page_ratio': '彩頁的彩色像素比例下限',
  'color:saturation': '彩色像素的飽和度下限',
  'freq:artist': '作者標籤的出現頁數比例下限',
  'freq:character': '角色標籤的出現頁數比例下限',
  'freq:copyright': '系列標籤的出現頁數比例下限',
  'freq:default': '其他類別的出現頁數比例下限',
  'freq:general': '一般標籤的出現頁數比例下限',
  'freqz:character': '角色標籤的頻率信心（標準差倍數）',
  'freqz:default': '其他類別的頻率信心（標準差倍數，0 為不使用）',
  'freqz:general': '一般標籤的頻率信心（標準差倍數）',
  'freqz:rating': '分級的頻率信心（標準差倍數，0 為不使用）',
  'rating:min_pages': '判定整部分級的最少頁數',
  'rating:score': '單頁分級的分數門檻',
  'sample:blank_ratio': '空白頁的近白近黑像素比例下限',
  'sample:floor': '每部的最少抽樣數',
  'sample:min_dimension': '送入模型的短邊像素下限',
  'sample:min_file_bytes': '內頁的檔案大小下限',
  'sample:near_black': '黑色的灰階上限',
  'sample:near_white': '白色的灰階下限',
  'sample:per_root': '每 √頁數 的抽樣數',
  'sample:tail_skip': '抽樣範圍（從開頭起的比例）',
  'sample:weight_early': '前段的抽樣比重',
  'sample:weight_late': '後段的抽樣比重',
  'sample:weight_middle': '中段的抽樣比重',
  'sample:zone_early': '前段的結束位置',
  'sample:zone_middle': '中段的結束位置',
  'score:artist': '作者標籤的分數門檻',
  'score:character': '角色標籤的分數門檻',
  'score:copyright': '系列標籤的分數門檻',
  'score:default': '其他類別的分數門檻',
  'score:general': '一般標籤的分數門檻',
  'type:comic': '漫畫的 comic 分數下限',
  'type:illust': '插畫的分數下限',
  'video:budget_base': '每部影片的基本抽格數',
  'video:budget_max': '每部影片的抽格數上限（0 為不限）',
  'video:budget_min': '每部影片的抽格數下限',
  'video:budget_per_minute': '每分鐘增加的抽格數',
  'video:frame_max_size': '畫格長邊的像素上限',
  'video:edge_margin': '片頭片尾各略過的比例',
  'video:scene_distance': '同一鏡頭的畫格差異上限',
  'worker:idle_release_s': '閒置後釋放模型的秒數',
}

export const EFFECT = {
  now: { text: '立即生效', tone: 'green' },
  next_scan: { text: '下次掃描生效', tone: 'blue' },
  rederive: { text: '會重新計算', tone: 'orange' },
}
