"""Tables of model definitions, their versions and the profiles that
group them."""

SQL = """
CREATE TABLE IF NOT EXISTS model_definitions (
    id           SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    source_text  TEXT NOT NULL,
    spec         JSONB NOT NULL,
    checksum     TEXT NOT NULL UNIQUE,
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    retracted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS model_versions (
    id            SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backend       TEXT NOT NULL,
    revision      TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    definition_id SMALLINT REFERENCES model_definitions(id),
    precision     TEXT NOT NULL CHECK (precision IN ('fp32', 'fp16')),
    state         TEXT NOT NULL DEFAULT 'ready'
                  CHECK (state IN ('building', 'ready', 'failed')),
    embedding_dim INTEGER,
    drift         REAL,
    error         TEXT,
    UNIQUE NULLS NOT DISTINCT (backend, revision, precision)
);

CREATE TABLE IF NOT EXISTS model_profiles (
    id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    active     BOOLEAN NOT NULL DEFAULT FALSE,
    maintained BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT model_profiles_active_maintained CHECK (NOT active OR maintained)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_model_profiles_active
    ON model_profiles ((TRUE)) WHERE active;

CREATE TABLE IF NOT EXISTS model_profile_members (
    profile_id       SMALLINT NOT NULL REFERENCES model_profiles(id) ON DELETE CASCADE,
    model_version_id SMALLINT NOT NULL REFERENCES model_versions(id),
    rank             SMALLINT NOT NULL,
    PRIMARY KEY (profile_id, model_version_id)
);

CREATE TABLE IF NOT EXISTS model_profile_roles (
    profile_id       SMALLINT NOT NULL,
    model_version_id SMALLINT NOT NULL,
    role             TEXT NOT NULL CHECK (role IN
                     ('general', 'character', 'copyright', 'artist', 'rating',
                      'embedding')),
    score_cutoff     NUMERIC CHECK (score_cutoff >= 0 AND score_cutoff <= 1),
    yields           BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (profile_id, model_version_id, role),
    FOREIGN KEY (profile_id, model_version_id)
        REFERENCES model_profile_members (profile_id, model_version_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS model_profile_params (
    profile_id SMALLINT NOT NULL REFERENCES model_profiles(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    value      NUMERIC NOT NULL,
    PRIMARY KEY (profile_id, name)
);
CREATE TABLE IF NOT EXISTS model_tags (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backend  TEXT NOT NULL,
    category TEXT NOT NULL,
    name     TEXT NOT NULL,
    UNIQUE (backend, category, name)
);
CREATE SCHEMA IF NOT EXISTS derived;
CREATE TABLE IF NOT EXISTS derived.tag_thresholds (
    model_version_id SMALLINT NOT NULL
                     REFERENCES model_versions(id) ON DELETE CASCADE,
    category         TEXT    NOT NULL,
    tag              TEXT    NOT NULL,
    threshold        NUMERIC NOT NULL CHECK (threshold >= 0 AND threshold <= 1),
    f1               REAL,
    source           TEXT    NOT NULL,
    PRIMARY KEY (model_version_id, category, tag)
);
CREATE INDEX IF NOT EXISTS idx_tag_thresholds_tag ON derived.tag_thresholds (tag);
"""


FUNCTIONS_SQL = """
CREATE OR REPLACE FUNCTION active_profile_id() RETURNS SMALLINT
LANGUAGE plpgsql STABLE SET search_path = pg_catalog, public AS $fn$
DECLARE v SMALLINT;
BEGIN
    SELECT id INTO v FROM model_profiles WHERE active;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'no model profile is active'
            USING HINT = 'set model_profiles.active on one maintained profile';
    END IF;
    RETURN v;
END
$fn$;

CREATE OR REPLACE FUNCTION derivation_param(p_profile SMALLINT, p_name TEXT)
RETURNS NUMERIC LANGUAGE plpgsql STABLE
SET search_path = pg_catalog, public AS $fn$
DECLARE v NUMERIC;
BEGIN
    SELECT value INTO v FROM model_profile_params
    WHERE profile_id = p_profile AND name = p_name;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'model profile % has no parameter named %',
            p_profile, p_name;
    END IF;
    RETURN v;
END
$fn$;
"""
